#!/bin/sh
#  ____                _____                  ___   ___
# |    \ ___ ___ _ _ _| __  |___ _ _ _ ___   |_  | |   |
# |  |  |  _| .'| | | |    -| .'| | | |  _|  |  _|_| | | 
# |____/|_| |__,|_____|__|__|__,|_____|_|    |___|_|___|
# ------------ A social website for artists ------------

COLOUR_RED="\033[0;31m"
COLOUR_BLUE="\033[0;36m"
COLOUR_GREEN="\033[0;32m"

BOLD="\033[1m"
NORMAL="\033[0m"

echo -e $COLOUR_GREEN " ____                _____                  ___   ___
 |    \ ___ ___ _ _ _| __  |___ _ _ _ ___   |_  | |   |
 |  |  |  _| .'| | | |    -| .'| | | |  _|  |  _|_| | |
 |____/|_| |__,|_____|__|__|__,|_____|_|    |___|_|___|
 ------------ A social website for artists ------------" $NORMAL "\n"

echo -e " [`date '+%F-%T'`] Evaluating your arguement:$BOLD $1 $NORMAL"

case $1 in
	"daemon") 
		echo " [`date '+%F-%T'`] Starting DrawRawr as a daemon..."
		
		echo -en $COLOUR_RED && python ./Main.py $@ & 2>&1 | echo 
		echo -en $NORMAL
		
		echo -e " [`date '+%F-%T'`]$COLOUR_GREEN Done!"
		;;
		
	"debug" | "no-daemon" | "normal")
		echo " [`date '+%F-%T'`] Starting DrawRawr normally (non-daemon)..."
		echo " [`date '+%F-%T'`] I/O is now DrawRawr. (:"
		
		python ./Main.py $@
		
		echo -e " [`date '+%F-%T'`]$COLOUR_GREEN Done! (DrawRawr closed)"
		;;
		
	"-h" | "--help" | "help")
		echo -e "\n Help for DrawRawr (arguements table)"
		echo -e " ====================================\n"
		
		echo -en $BOLD "daemon"
		echo -e $NORMAL "| runs DrawRawr in production daemonized mode."
		
		echo -en $BOLD "debug" -or- "no-daemon"
		echo -e $NORMAL "| runs DrawRawr in debug mode (daemonized mode)."
		;;
	
	*) 
		echo -e $COLOUR_RED "\n No arguement specified." $NORMAL
		echo " Perhaps you'd like to run $0 --help ?" 
		;;
esac
